// ONE-TIME MIGRATION: Run this once to load existing blogs into database
// Visit: https://seo-tools-lake.vercel.app/api/migrate

const EXISTING_BLOGS = [
  "How To Hang Canvas Prints Without Nails",
  "How To Measure Wall For Art",
  "How To Measure A Picture Frame",
  "How To Measure Artwork For Framing",
  "How To Put Up Wall Art",
  "Are Floating Frames Worth It",
  "How Does A Floating Frame Work",
  "Are Floating Frames Good",
  "Should I Frame Canvas Prints",
  "Is Acrylic Better Than Glass For Picture Frames",
  "Are Acrylic Frames Better Than Glass",
  "Is Museum Glass Better Than Acrylic",
  "Are Acrylic Prints Worth It",
  "What Are UV Acrylic Sheets",
  "Should Canvas Art Be Framed",
  "Should You Frame A Canvas Print",
  "Do Canvas Paintings Need To Be Framed",
  "Is It OK To Frame A Canvas Painting",
  "Is It Better To Frame A Canvas Painting",
  "Can You Frame Stretched Canvas",
  "Should You Put Glass Over A Canvas Print",
  "Do You Put Glass Over Canvas Art",
  "Can You Laminate A Canvas Print",
  "How To Clean Dust Off Canvas Print",
  "Can You Use Windex On Acrylic",
  "How Do You Clean Cloudy Acrylic",
  "Can I Use Glass Cleaner On Plexiglass",
  "Can You Clean Acrylic With Vinegar",
  "Can You Use Windex On Plexiglass",
  "Does Acrylic Yellow Over Time",
  "Does UV Acrylic Yellow",
  "Does Acrylic Turn Yellow In Sunlight",
  "Will Acrylic Yellow",
  "What Is A Floating Frame",
  "What Is Acrylic Perspex",
  "What Is UV Acrylic",
  "What Does UV Acrylic Mean",
  "What Is Anti Reflective Acrylic",
  "What Is UV Filtering Acrylic",
  "What Are Clip Frames",
  "What Is Museum Glass",
  "What Is Museum Quality Framing",
  "What Is Museum Glass For Picture Frames",
  "What Is Museum Quality Glass",
  "What Is Non Glare Glass",
  "What Is The Best Non Reflective Glass For Picture Frames",
  "What Is The Difference Between Museum Glass And Regular Glass",
  "What Is Anti Reflective Glass",
  "What Is Conservation Framing",
  "What Is A Mat In Picture Framing",
  "What Is Wrapped Canvas",
  "What Is A Gallery Wrapped Canvas",
  "What Is A Museum Wrapped Canvas",
  "What Is A Mirror Wrapped Canvas",
  "What Is Box Framing",
  "What Is Box Canvas",
  "What Does Gallery Wrap Mean",
  "What Does Gallery Wrapped Canvas Mean",
  "What Is Moulding In Picture Frames",
  "What Is Stretcher Bar Depth",
  "What Size Frame Do I Need For A 12x16 Print",
  "What Size Picture Frame Do I Need",
  "What Size Frame For 16x20 Mat",
  "What Does 16x20 Matted To 11x14 Mean",
  "What Frame Size For A4",
  "Do Canvas Prints Fade",
  "Do Acrylic Prints Fade",
  "Do Canvas Prints Fade In Sunlight",
  "Can Acrylic Prints Get Wet",
  "Do Canvas Prints Need Glass",
  "Does Canvas Print Mean No Frame",
  "What Does Unframed Canvas Print Mean",
  "Do I Need To Frame A Canvas Print",
  "Can Canvas Prints Be Framed",
  "Does Canvas Need To Be Stretched Before Framing",
  "Can You Put A Stretched Canvas In A Frame",
  "Can You Frame An Unstretched Canvas",
  "How Do You Attach A Canvas To A Frame",
  "How To Frame A Rolled Canvas Print",
  "How To Frame A Canvas Print DIY",
  "How To Frame Canvas Painting At Home",
  "How To Frame Unframed Canvas",
  "Can You Cut A Canvas Print",
  "Can You Make A Canvas Print Smaller",
  "Can You Put Canvas In A Glass Frame",
  "Can Canvas Art Have Glass",
  "Can You Put A Frame Around A Canvas Print",
  "How To Put A Stretched Canvas In A Frame",
  "How To Attach Canvas To Wooden Frame",
  "How To Make A Canvas Float Frame",
  "How To Hang Floating Frame",
  "How To Make A Floating Canvas Frame",
  "How To Display Canvas Prints",
  "How To Install Floating Frame",
  "Are Canvas Prints Tacky",
  "Is Canvas A Cheap Print",
  "Can You Wash A Canvas Print",
  "Can You Iron A Canvas Print",
  "Can You Restretch A Canvas Print",
  "Are Posters Tacky",
  "Is It OK To Put Poster In Bedroom",
  "How To Mount Poster On Foam Board",
  "How To Stick Posters On Wall Without Leaving Marks",
  "How To Put Posters On Wall Without Damaging Paint",
  "How To Hang A Poster Without A Frame Or Nails",
  "How To Frame Posters Cheaply",
  "How Do You Frame A Poster Without Spending A Lot Of Money",
  "How Can I Frame A Picture Cheaply",
  "How To Make Cheap Frames Look Expensive",
  "Can You Frame A Poster In A Picture Frame",
  "Can Any Frame Be A Poster Frame",
  "Can You Use A Picture Frame For A Poster",
  "What Frame To Use For Poster",
  "Should I Frame My Poster",
  "Should You Frame Posters With Glass",
  "Is It Better To Roll Or Fold A Poster",
  "How Do You Flatten A Poster That Has Been Rolled",
  "How Do You Display Posters Without Frames",
  "Do Posters Look Better Framed",
  "Should I Put Posters In My Room",
  "How To Display Posters Nicely",
  "Should Posters Be Matted",
  "Should I Get Poster Framed",
  "What Is Standard Poster Frame Size",
  "What Size Frame For 24x36 Poster",
  "How Much Does It Cost To Get A Poster Framed",
  "How To Flatten Rolled Canvas Print",
  "How To Remove Wrinkles From Canvas Print",
  "How To Flatten Creased Canvas",
  "How To Get Creases Out Of Canvas Without An Iron",
  "Can You Steam A Canvas Print",
  "How Do I Display Art Prints Without Frame",
  "How To Display Pictures Without Hanging",
  "How To Hang Pictures On Wall Without Drilling",
  "How To Hang Canvas Without Damaging Wall",
  "How To Hang Canvas Without Nails",
  "How To Hang Heavy Canvas Without Nails",
  "How To Hang Unframed Canvas",
  "How To Hang Rolled Canvas",
  "How Do You Hang A Canvas Print",
  "Can You Hang Canvas With Command Strips",
  "Will Command Strips Hold Up Canvas",
  "How Much Weight Can Command Strips Hold",
  "What Is The Strongest Command Strip",
  "How To Hang Canvas With Command Strips",
  "How To Make Canvas Prints Look Professional",
  "What Is Better Framed Or Unframed Canvas",
  "Should Canvas Art Be Matted",
  "Should Canvas Be Framed With A Mat",
  "Do You Put A Mat On A Canvas",
  "Should I Mat My Canvas Print",
  "Can You Use Canvas Board For Painting",
  "What Is The Difference Between Canvas Panel And Canvas Board",
  "Should You Wet Your Canvas Before Acrylic Painting",
  "Should You Paint A Canvas White First",
  "Can You Paint Over A Printed Canvas",
  "Can You Put Glass Over An Acrylic Print",
  "Should Acrylic Prints Be Framed",
  "Do Acrylic Prints Need To Be Framed",
  "What Is The Difference Between Acrylic And Glass Prints",
  "Are Acrylic Prints Worth The Money",
  "Do Acrylic Prints Look Cheap",
  "How Long Do Acrylic Prints Last",
  "Are Acrylic Prints Good Quality",
  "How To Clean Acrylic Print",
  "How Do You Hang Acrylic Prints",
  "How To Mount Acrylic Print",
  "What Is A Metal Print",
  "Are Metal Prints Worth It",
  "Do Metal Prints Fade",
  "Are Metal Prints Better Than Canvas",
  "Do Metal Prints Need To Be Framed",
  "Should You Frame Metal Prints",
  "Can You Frame A Metal Print",
  "How To Hang Metal Prints",
  "How To Clean Metal Prints",
  "What Are Giclee Prints",
  "Are Giclee Prints Worth It",
  "How Long Do Giclee Prints Last",
  "What Is The Difference Between An Art Print And A Giclee Print",
  "What Is The Difference Between A Photograph And A Giclee",
  "How Do I Know If My Print Is Giclee",
  "What Is Better Giclee Or Canvas",
  "Can You Print Giclee At Home",
  "How Much Should I Charge For Giclee Prints",
  "How To Frame Giclee Print",
  "Should You Frame Prints",
  "Should Art Prints Be Framed",
  "Is It Better To Frame A Print",
  "How Do You Display Art Prints",
  "How To Display Art Prints On Wall",
  "How To Display Unframed Art Prints",
  "How To Frame Art Prints At Home",
  "How To Frame Art Prints Cheaply",
  "How Much Does It Cost To Get Art Print Framed",
  "What Size Frame Do I Need For An A4 Print",
  "What Is Standard Picture Frame Size",
  "What Is The Most Popular Picture Frame Size",
  "What Is The Most Common Frame Size For Pictures",
  "What Size Frame For 8x10 Photo With Mat",
  "What Size Frame For 5x7 Photo With Mat",
  "What Size Mat For 11x14 Frame",
  "How Much Should A Mat Overlap A Picture",
  "How Far Should A Mat Overlap A Picture",
  "What Colour Mat Looks Best",
  "Should Picture Mats Be White Or Cream",
  "Should I Use A White Or Cream Mat",
  "What Color Mat For Black And White Photo",
  "Should Mat Be Lighter Or Darker Than Picture",
  "How Do I Choose A Mat Color",
  "What Is The Best Mat Color For Artwork",
  "How To Choose Mat Color For Framing",
  "What Is A Double Mat",
  "Should You Double Mat A Picture",
  "What Is The Purpose Of A Double Mat",
  "How Much Does Picture Framing Cost",
  "Why Is Custom Framing So Expensive",
  "How Much Does It Cost To Get A Picture Professionally Framed",
  "How Much Does It Cost To Frame A Canvas",
  "Is It Cheaper To Make Your Own Picture Frames",
  "How To Frame A Picture Yourself",
  "How To Frame A Picture Without A Frame",
  "How To Frame A Picture Cheaply",
  "How To DIY Picture Frame",
  "What Is The Easiest Way To Frame A Picture",
  "Can I Frame A Picture Myself",
  "What Do You Need To Frame A Picture",
  "What Is The Best Way To Hang Pictures",
  "How High Should Art Be Hung",
  "How High To Hang Pictures On Wall",
  "How High Should You Hang A Picture Above A Couch",
  "How High Should Pictures Be Hung Above Furniture",
  "What Is The Rule For Hanging Pictures",
  "What Is The 57 Inch Rule For Hanging Pictures",
  "Should All Pictures Be Hung At The Same Height",
  "How To Hang Pictures Evenly",
  "How To Arrange Pictures On A Wall",
  "How To Layout Pictures On A Wall",
  "How Far Apart Should Pictures Be Hung",
  "How To Hang Multiple Pictures",
  "How To Hang 3 Pictures In A Row",
  "How To Hang 4 Pictures The Same Size",
  "How To Arrange 3 Pictures On A Wall",
  "What Is A Gallery Wall",
  "How To Create A Gallery Wall",
  "How To Arrange A Gallery Wall",
  "How To Plan A Gallery Wall Layout",
  "How Far Apart Should Gallery Wall Pictures Be",
  "Should Gallery Wall Frames Match",
  "How Many Pictures Should Be In A Gallery Wall",
  "How To Hang A Gallery Wall Without Nails",
  "What Is The Best Way To Hang Heavy Pictures",
  "How To Hang Heavy Frames",
  "How Much Weight Can A Picture Hook Hold",
  "How To Hang Pictures On Plasterboard",
  "How To Hang Pictures On Drywall",
  "How To Hang Pictures Without Making Holes",
  "Can You Hang Pictures With Command Strips",
  "Do Command Strips Work For Heavy Pictures",
  "How To Hang Pictures With Command Strips",
  "How To Remove Command Strips Without Damaging Wall",
  "What Can I Use Instead Of Command Strips",
  "How To Hang Pictures On Brick Wall",
  "How To Hang Pictures On Concrete Wall",
  "How To Hang Pictures On Tile Wall",
  "Can You Nail Into Tile",
  "How To Hang Art On Textured Walls",
  "How To Display Art Without Damaging Walls",
  "What Is Museum Putty",
  "How To Use Museum Putty",
  "Does Museum Putty Damage Walls",
  "What Is Better Than Command Strips",
  "What Is Picture Rail Molding",
  "How To Use Picture Rail",
  "How To Hang Pictures From Picture Rail",
  "What Is The Best Height For Picture Rail",
  "What Is Picture Wire",
  "How To Attach Picture Wire To Frame",
  "How To String Picture Wire",
  "What Is D Ring Picture Hanger",
  "How To Install D Rings On Picture Frame",
  "Should D Rings Be Level",
  "What Is Sawtooth Hanger",
  "How To Install Sawtooth Picture Hanger",
  "How To Hang Picture With Sawtooth Hanger",
  "Are Sawtooth Hangers Strong Enough",
  "What Is French Cleat",
  "How To Install French Cleat For Pictures",
  "How To Make A French Cleat Picture Hanger",
  "How Much Weight Can A French Cleat Hold",
  "What Is The Strongest Way To Hang A Picture",
  "How To Hang Very Heavy Mirror",
  "How To Secure Picture Frame To Wall",
  "How To Stop Pictures From Tilting",
  "How To Keep Pictures Straight On Wall",
  "Why Do My Pictures Keep Falling Off The Wall",
  "How To Fix Picture Frame That Won't Stay Level",
  "What Is Conservation Glass",
  "What Is The Difference Between Conservation Glass And Museum Glass",
  "Is Conservation Glass Worth It",
  "What Is UV Protective Glass",
  "Does UV Glass Really Work",
  "How Long Does UV Glass Last",
  "What Is The Best Glass For Framing Artwork",
  "What Is The Difference Between Regular Glass And Museum Glass For Picture Frames",
  "Is Museum Glass Worth The Money",
  "What Is Reflection Control Glass",
  "What Is The Difference Between Anti Reflective And Non Glare Glass",
  "How To Reduce Glare On Framed Pictures",
  "How Do You Stop Glass From Reflecting In A Picture Frame",
  "What Is The Least Reflective Glass",
  "What Is TruVue Museum Glass",
  "Is TruVue Glass Worth It",
  "What Is Optium Museum Acrylic",
  "Is Optium Acrylic Worth It"
];

function extractKeyword(title) {
  const questionWords = /\b(how|what|why|when|where|which|who|is|are|can|do|does|should|will)\b/gi;
  const endings = /\b(guide|tips|ideas|ways|steps|tricks|hacks|secrets|benefits|mistakes|examples|like a pro|for beginners|101|explained|ultimate|complete|best|top)\b/gi;
  const fillers = /\b(a|an|the|your|my|our|for|in|on|at|to|of|with|and|or|but)\b/gi;
  
  let keyword = title.toLowerCase()
    .replace(questionWords, '')
    .replace(endings, '')
    .replace(fillers, '')
    .replace(/[^\w\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(word => word.length > 2)
    .slice(0, 4)
    .join(' ');
  
  return keyword || title.toLowerCase();
}

import { put } from '@vercel/blob';

export default async function handler(req, res) {
  try {
    // Convert to database format
    const blogs = EXISTING_BLOGS.map(title => ({
      title,
      keyword: extractKeyword(title),
      status: 'published',
      date: '2026-01-01',
      url: null
    }));

    // Save to blob storage (private access)
    await put('blogs.json', JSON.stringify(blogs, null, 2), {
      access: 'private',
      contentType: 'application/json'
    });

    return res.status(200).json({ 
      success: true, 
      message: `Migrated ${blogs.length} blogs to database`,
      count: blogs.length
    });

  } catch (error) {
    console.error('Migration error:', error);
    return res.status(500).json({ error: error.message });
  }
}
