const { put } = require('@vercel/blob');

function extractKeyword(title) {
  const questionWords = /\b(how|what|why|when|where|which|who|is|are|can|do|does|should|will)\b/gi;
  const endings = /\b(guide|tips|ideas|ways|steps|tricks|hacks|secrets|benefits|mistakes|examples|like a pro|for beginners|101|explained|ultimate|complete|best|top)\b/gi;
  const fillers = /\b(a|an|the|your|my|our|for|in|on|at|to|of|with|and|or|but)\b/gi;
  
  let keyword = title.toLowerCase()
    .replace(questionWords, '')
    .replace(endings, '')
    .replace(fillers, '')
    .replace(/[^\w\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(word => word.length > 2)
    .slice(0, 4)
    .join(' ');
  
  return keyword || title.toLowerCase();
}

const SHOPIFY_BLOGS = [
"7 Tips to transform Your Home office decor with Calming Wall Art",
"Zen Decor Ideas: Calm & Serenity in Your Living space",
"5 Calming Wall Art Ideas to create a Relaxing bedroom decor",
"The Essence of Scandinavian Interior Design",
"Transform Your Home into a Winter Wonderland with Wall decor Christmas",
"Illuminate Your Home Decor this Eid with Modern Islamic Art",
"The Symbolism Behind Wedding Anniversary Gifts by Year",
"The Impact of Modern Wall Art on Contemporary Home Decor",
"The Art of Decorating: Modern master bedroom decor ideas",
"Enhancing your baby's room with the cutest Wall art for nursery ideas",
"Transform Your Home into a Coastal Haven with Tropical Home Decor",
"How to Design & Create a Retreat with wall art ideas for bathroom",
"How to Decorate a Large Wall in a Living Room with Wall art",
"Top 8 Coastal Decor Home Ideas on a budget",
"How Mid century modern interior decor uses Wall Art as Conversational Pieces",
"The Fusion of Japanese Minimalism & Scandinavian Decor",
"Exploring the World from Your Living Room: Travel Posters",
"Exploring the Beauty of Eclectic interior decor",
"Exploring office Wall Art Prints when designing a Home office decor",
"Creating a charming Home with Timeless French Country interior Decor",
"Create a Serene Retreat: Transform Your Space with Farmhouse Decor",
"Birthstone presents: Finding the perfect gift for an Astrology lover",
"10 Creative Kitchen wall decor ideas",
"Transforming Spaces: Unveiling the Power of Japan prints and Feng Shui",
"Choosing the Right Wall Art for Living Room: Tips, Trends, and Recommendations",
"Dive into the History of Islamic Calligraphy wall art and Its Modern Appeal",
"Top 8 Hallway Art Ideas to Transform Your Space",
"Mesmerising Spaces: Elevate Your Space with teal color wall art",
"Embrace Nature's Palette using Earth tone colors",
"Neutral Wall Decor: Elevate Your Space with Timeless Tranquility",
"Gilded Opulence: Elevate Your Space with Gold Wall Art Decor",
"Elevate Your Just married First Home Decor with Wall art about love",
"Personalised family presents for Everlasting Memories",
"Unique Birthday Presents to Celebrate Beyond Ordinary",
"Bohemian Bliss: Elevate Your Space with Bohemian art wall",
"10 Tips for Decorating Your Yoga Studio with Spiritual home decor",
"Elevate Your Space: Small Bathroom Wall Art Ideas to Inspire Refreshing Moments",
"Top 5 Islamic art wall Ideas Revealed",
"8 Creative Bathroom Wall Art Ideas to Transform Your Space",
"Bible scripture wall art prints to Inspire your Home decor",
"From East to West: Chinoiserie Wall murals in home Interiors",
"Trending now: Wall art pictures for living room in Grounded Colours",
"Black and White Magic: Creating Bold Galleries with Framed Wall Art",
"Blossoming Trends: Botanical Wall Art for Bedroom",
"Inspiring Wall Gallery Layouts : From Blank Walls to a Perfect Gallery",
"Get the Boho Look: 9 DIY Boho Home Decor Ideas for Every Room",
"Cherry Blossom Art Japan: Understanding the Deep Symbolism",
"Christmas Decor Ideas Beyond the Tree: 8 Fresh Ideas for a Festive Home",
"Decorating with Framed Artwork Prints",
"12 Small restroom decor ideas to maximise space",
"Wall Arts for Living Room: Wallpaper vs Wall art",
"Living Room Fireplace Decor Ideas: Step-by-Step Guide to a Makeover",
"From Drab to Fab: Black and White Bathroom Design Ideas for a Makeover",
"From Blank to Beautiful: Gallery Wall Ideas for Huge Walls",
"Beach House Decor: Embrace the Shibori Trend for a Unique Coastal Vibe",
"Decor for the Home: Choosing the Perfect Vibes for Your Home Decor",
"How to decorate Japandi Style interiors (and what it is?)",
"Small Studio Apartment Decor: 10 Genius Tips & Hacks for Maximising Space",
"Never Too Small: Wall Decoration Office Ideas for Tiny Apartments",
"Greige colours: How to decorate with the timeless blend of Grey & Beige",
"Step-by-Step Guide: What Frame Size Do I Need for my Space",
"Choosing the Right Palette: What Colour Goes with Grey Walls? Essential Tips",
"Inspiring Laundry Room Decor: Tips for a Functional and Beautiful Space",
"Corridor Decor Ideas: Transforming Your Hallways with Style",
"8 Creative teenage bedroom decor ideas",
"How to decorate a bathtub and transform your Bathroom",
"How to Decorate Hallways to Maximise Space. Quick Tips and Tricks",
"How to Decorate a Really Small Bedroom: 10 Space-Saving Tips and Tricks",
"Bringing Scandinavian Design decor into Your Home",
"Can a single, Abstract Art transform the energy of your living space?",
"Want to turn plain walls into a stunning, cozy interiors retreat with creative layers?",
"How to create a wow factor with the right Living room Wall Art Decor!",
"Bathroom Art Ideas to transform your small bathroom into an oasis",
"Transform your bedroom into a sanctuary! Discover perfect Above the bed decor ideas",
"Transform your home into an walk in the woods oasis using Biophilic Design",
"How to Use Typography for a Playful Kitchen Wall Art Decor?",
"How to effortlessly mix and blend different art style types in a living room?",
"How could your art for an office wall fuel creativity and productivity?",
"How can the right Bedroom Art Ideas transform your space for sleep and relaxation?",
"How a single wall can transform your Space Bedroom Decor into a stunning sanctuary?",
"Atmosphere with Art: Transform Your Space Faster Than a Fresh Coat of Paint!",
"Did you know that the Bedroom Wall Art ideas you choose can impact your quality of rest?",
"Can the right Art For The Kitchen turn it into an inviting space?",
"From Dull to Dazzling: The Best Art For A Kitchen Wall Ideas",
"How nature-inspired art can transform your walls into a soul-soothing masterpiece?",
"Budget Dining Area Decor Ideas That Instantly Elevate the Room",
"Solving Wall Blankness with Well-Placed Pictures for Lounge Rooms",
"Solving Moisture Problems with Safe Bathtub Decor Ideas",
"Rustic Decoration for Home That Doesn't Feel Dated",
"Moisture Resistant Restroom Wall Art What Actually Works",
"How to Use Color Psychology in Interior Design",
"How to Use Art On Walls to Anchor a Color Scheme",
"How to Select the Right Pictures Frames for Your Artwork",
"How to Match Prints For The Wall with Your Interior Color Scheme",
"Feng Shui bedroom: Tips and Tricks",
"Elegant Ways to Incorporate the Dua of Forgiveness into Modern Islamic Decor",
"Common Mistakes When Estimating the Size of a Frame for Wall Art",
"Canvas wall arts vs. Framed Prints: What's Best for Each Room?",
"10 creative ideas for decorating your living room wall on a budget",
"Choosing the right art for grey walls without making the room feel cold",
"Coastal decor bedroom ideas: How to style this new trend it?",
"What to do when your home lacks natural light: Decorate living room wall hangings",
"What interior stylists predict for the next 5 years: Home decor design trends",
"Using wall art to complement color schemes in bedrooms",
"The new neutrals trend: Beyond beige modern wall arts",
"The case for empty spaces: When less truly is more",
"Style trends: Add a dash of drama with the wild side look for your home",
"Fresh interior decor ideas for living room updates",
"Solving lighting challenges when using a Deep Winter colour palette",
"Solving last minute gifting with elegant Xmas decorations personalised",
"Solving focal point issues with the right Sitting room art",
"Solving dull vibes: Add personality with easy dining room decor",
"The clash of 2025: Bold vs Muted color trends in home decor",
"How to use decor to improve daily habits",
"How to use a Nursery Decor style that grows with your child",
"How to hang wall art for stairs without a straight wall",
"How to add personality without overstimulating young minds: Nursery Colours",
"Fixing a room with too much Neutral Tones",
"Earth inspired living: The volcano and forest palettes down to earth colour trends",
"Do beige and grey go together? Here's how to make it work…",
"Designing a living room decor wall space",
"Designing a clutter free kids playroom: Childrens Playroom ideas",
"Decor for Nursery Wall that stimulates without overwhelming",
"Creating a Gallery wall feel in a small flat",
"Common mistakes in Colour schemes living room designers avoid",
"Rental Decor: How to Make a Rental Feel Like Home Without Getting in Trouble",
"Solving Extra Large Wall Art placement anxiety where and how to hang",
"Wall Art for Living Room: Inspiring Ideas and Expert Tips",
"Modern Wall Art Ideas to Refresh Any Space",
"Art for Offices: Inspiring Ideas for Every Workspace",
"What is Wall Art? A Complete Guide to Transforming Your Space",
"Stylish Prints for Living Room: Inspire Your Space",
"Canvas Paintings for Living Room: Stylish Ideas and Tips",
"10 Popular Types of Wall Art for Every Space",
"Essential Tips for Moving House: A Stress-Free Guide",
"How to Choose the Perfect Art for Bedrooms",
"How I Used Canvas Pictures for Living Rooms to Create My Calm Sanctuary",
"Creating Calm with Minimalist Living Decor",
"First Apartment Essentials: Ultimate Guide for Every Home",
"How to Hang Art: Easy Steps for Perfect Display",
"Understanding Wall Art Size Guide for Your Space",
"8 Smart Small Space Decorating Ideas for Your Home",
"7 Soothing Color Palettes for Your Home and Office",
"What is Canvas Art? Understanding the Beauty and Impact",
"10 Office Decor Ideas to Boost Your Productivity",
"Understanding the Role of Art in Interior Design",
"7 Home Decor Trends 2025 You Need to Know Now",
"Understanding Interior Decorating Terms for Everyone",
"7 Essential Tips for Wall Art Hanging Systems",
"7 Inspiring Tips for Nature Inspired Wall Art",
"7 Inspiring Ideas for Wall Art for Teenagers",
"7 Creative Ideas for Wall Art for High Ceilings",
"7 Creative Ideas for Decorating the Home",
"Understanding Art and Wellbeing: Impact and Insights",
"Understanding Art Color Meaning: Emotions and Symbolism",
"8 Fresh Ideas for Inspiration for Home Decor",
"7 Smart Tips for Decorating on a Budget",
"8 Essential Tips to Shop Online Decoration for Home",
"8 Inspiring Abstract Wall Art Ideas for Any Space",
"7 Smart Tips for Choosing Art for Small Spaces",
"7 Accent Wall Art Ideas for a Stunning Home",
"7 DIY Accent Wall Ideas to Transform Your Space",
"Understanding Landscape Art Styles: What They Are and Why They Matter",
"Current Home Decor Trends Transforming Spaces in 2025",
"Stylish Bedroom Ideas to Create the Perfect Guest Room",
"Design Lounge Room: Feels Effortlessly Stylish",
"Explore the Most Popular Home Decor Styles for Every Space",
"A Guide to Finding Your Home Decor Style",
"How To Find Your Perfect Home Decor Styles",
"Top Decorations for Master Bedrooms to Elevate Your Space",
"Creative Dining Area Interiors to Inspire Your Home",
"Guest Bedroom Decorating Ideas for a Warm and Welcoming Space",
"Fun and Stylish Decorating Ideas for a Teenage Bedroom",
"Stylish Practical Decorating Tips for Family Room",
"Creative Children's Room Wall Decorations to Brighten Their Space",
"Fresh Ideas for Sitting Room Designs to Transform Your Space",
"My Guide to Decorate a Powder Room with Style",
"What is Minimalist Art? The Beauty of Less is More",
"Essential Tips for Gallery Wall Planning to Showcase Your Style",
"Creative Office Wall Design Ideas to Inspire Productivity",
"Creating a Stylish Retreat with black and white wall art for bedroom",
"Chic Pink Room Ideas for a Stylish and Fun Space",
"Creative Wall Decor Ideas for Large Walls to Transform Your Space",
"Creative toilet decorations to Elevate Your Small Bathroom",
"Stylish Ideas for Your Perfect Dine In Room",
"Essential Tips for Man Decorating: Stylish Ideas for Every Space",
"How to Find Your Decorating Style: A Guide to Personalised Interiors",
"Stylish man cave decorations for wall: Personalise Your Space",
"How To Live A Minimalist Life And Thrive With Simplicity",
"Creative Study Room Decor Ideas to Boost Focus and Style",
"Stylish Bathroom En Suite Ideas to Elevate Your Space",
"My Friendly Guide to Designing a Playroom Your Kids Will Adore",
"Family Room Interiors to Inspire Comfort and Togetherness",
"The Role of Wall Art in Mood Setting: Enhance Your Space with Style",
"Smart Ways to Decorate a Professional Office for Style and Productivity",
"How to Create a Relaxing Workspace: Practical Ways to Support Mental Health at Work",
"Awesome Bedroom Ideas to Transform Your Space",
"Inspiring Interior Design Ideas for Bedrooms: Creating Your Calm Sanctuary",
"Creative Ideas for a Fun and Functional Childrens Bedroom",
"Stylish Ideas for Lounge: Create Comfort and Elegance",
"Inspiring Main Bedroom Decoration Ideas for Comfort and Style",
"Stylish Powder Room Bathroom Decorating Ideas to Elevate Your Space",
"Decorating Trend: Japandi Style - How To Create A Calm Home",
"Nice Sitting Room Designs to Inspire Comfort and Style",
"What is Typographic Art: Exploring Words as Visual Design",
"How to Decorate a Master Bedroom: Stylish Ideas for Comfort and Luxury",
"Ever Wondered Why Art Placement Is Important for Your Home's Vibe?",
"Why Refresh Wall Decor: Transform Your Space with Ease",
"Types of Wall Art Materials: A Guide to Choosing the Perfect Finish",
"Color Psychology in Art: Understanding How Shades Shape Emotion",
"Best Plants for Offices: Bring Life and Calm Into Your Workspace",
"What is the 3-5-7 rule in Decorating: A Simple Formula for Stylish Spaces",
"A Journey Through The History of Wall Art",
"Essential Accessories for Living Room Decor to Elevate Your Space",
"Art as Stress Relief: How Creativity Can Calm the Mind",
"How big should wall art be above a sofa?",
"Japandi Home Decor: A Calm and Minimal Blend of East Meets West",
"What Is Minimalist Wall Art: Simplicity That Speaks Volumes",
"Wall Decor Modern Ideas to Refresh Any Room",
"Art Print vs Poster: What's the Difference and Which Should You Choose?",
"The Role of Colour in Office Spaces: Create Productivity Through Design",
"Tips for Using Wall Art Decor for Bedroom to Elevate Your Space",
"Why Art Matters in Offices: Boost Productivity and Inspire Creativity",
"Define Minimalism: Understanding the Art of Simple Living and Design",
"Coastal Interior Design: Bring the Beach Home with These Ideas",
"Bohemian Living Room Ideas: Free-Spirited Decor Tips",
"Living Room Boho Wall Art: Express Your Bohemian Style",
"Boho Bedroom Ideas: Create Your Peaceful Sanctuary",
"Home Decor Trends for 2026: Key Looks for Every Room",
"Home Decor Trends Now: What People Are Actually Buying in 2026",
"Interior Design Trends for 2026: What's In and What's Out",
"Interior Design Trends for 2026: Key Looks to Try",
"Current Interior Decorating Trends for 2026 You Need to Know",
"What Are the Benefits of Buying Local Wall Art?",
"How to Incorporate Wall Art into Your Home Office",
"Should I Hire an Interior Designer for My Small Space?",
"How Big Should My Wall Art Be?",
"What's the Difference Between Canvas and Framed Prints?",
"How to Hang Wall Art Like a Pro",
"Should I Commission Custom Wall Art?",
"How to Style a Gallery Wall",
"How Much Wall Art Do I Need for My Space?",
"What's the Difference Between Digital and Handmade Wall Art?",
"How to Choose Wall Art for Rental Spaces",
"What Wall Art Mediums Are Available?",
"How to Incorporate Cultural Wall Art into Your Home",
"How to Mix and Match Wall Art Styles",
"How Can I Get the Most Value from Hiring an Interior Designer?",
"Should I Hire an Interior Designer for My Rental Apartment?",
"How Can I Prepare My Home for an Interior Designer Consultation?",
"What are the Top 5 Interior Design Trends for This Year?",
"How Can I Incorporate Sustainable Design Into My Home?",
"What are the Best Interior Design Ideas for Small Spaces?",
"How Can I Update My Home's Curb Appeal on a Budget?",
"What Home Decor Essentials Should I Invest In?",
"How Can I Incorporate Timeless Design Into My Home?",
"What's the Difference Between an Interior Decorator and Designer?",
"How Can I Refresh My Living Room on a Budget?",
"What are the Benefits of Hiring an Interior Designer for My Home?",
"How Can I Incorporate Feng Shui Principles Into My Home Design?",
"How to Style Your Home Like a Professional",
"The Best Online Tools for Interior Design Planning",
"The Dos and Don'ts of Mixing Patterns in Interior Design",
"How to Incorporate Sustainable Materials in Your Interior Design",
"Top Interior Design Trends to Watch for in the Coming Year",
"Design Tips for Compact Homes",
"How Much Does an Interior Decorator Cost?",
"Is Hiring an Interior Decorator Worth It?",
"How to Choose the Perfect Interior Decorator for Your Home",
"Should I Hire an Interior Decorator or Do It Myself?",
"What to Expect When Working with an Interior Decorator",
"How to Prepare for Your First Meeting with an Interior Decorator",
"Can an Interior Decorator Help Me Stay on Budget?",
"How Much Should I Budget for Wall Art?",
"What Type of Wall Art Fits My Home Style?",
"Large Wall Decor Ideas to Fill Big Blank Walls Beautifully",
"Best Wall Art Ideas Bedroom for Small Spaces and Apartments",
"How Wall Art Ideas For Bedroom Can Completely Change Your Space",
"Small Studio Design Ideas: Small Space Design Solutions for 2026",
"Study Room Decoration Ideas to Boost Focus and Motivation",
"Bathroom Above Toilet Decor: Transform That Empty Space",
"Space Temporary Cultural: Practical Design Insights for Modern Interiors",
"Everything You Need About Perfect How To Decorate A Large Wall In Living Room",
"How to Care for and Maintain Wall Art",
"How to Use Wall Art to Brighten a Dark Room"
];

module.exports = async function handler(req, res) {
  try {
    const blogs = SHOPIFY_BLOGS.map(title => ({
      title,
      keyword: extractKeyword(title),
      status: 'published',
      date: '2026-01-01',
      url: null
    }));

    await put('blogs.json', JSON.stringify(blogs, null, 2), {
      access: 'public',
      contentType: 'application/json',
      token: process.env.BLOGDATA_READ_WRITE_TOKEN
    });

    return res.status(200).json({ success: true, total: blogs.length });

  } catch (error) {
    console.error('Error:', error);
    return res.status(500).json({ error: error.message });
  }
};
